name: Build and publish the Docker image to ghcr.io
on:
  release:
    types: [ published ]
  push:
    branches:
      - main

jobs:
  docker_publish:
    runs-on: "ubuntu-20.04"

    steps:
      - uses: actions/checkout@v4

      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: mbaum0/badsec
          github_token: ${{ secrets.GHCR_TOKEN }}
